version : '3'

services:
  postgres:
    image: postgres:11.4

  website:
    build: .
    command: 
      /bin/bash -c "
        pip-sync requirements/requirements.txt &&
        python manage.py migrate &&
        python manage.py runserver 8000"
    ports:
      - 9080:8000
    depends_on:
      - postgres