# Generated by Django 3.2.8 on 2021-12-07 20:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20211207_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='equipment',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hitDieTotal',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='character',
            name='inspiration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
